import type { Alert, Rule, LogEntry, SystemStats, BlockedIP, AttackStats, TimelineData } from '@/types';

// Mock Alerts Data
export const mockAlerts: Alert[] = [
  {
    id: '1',
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    severity: 1,
    category: 'DDoS Attack',
    signature: 'ET DOS Possible NTP DDoS Inbound Frequent Un-Authed MON_LIST Requests',
    srcIp: '185.220.101.45',
    srcPort: 54321,
    destIp: '192.168.1.100',
    destPort: 80,
    protocol: 'TCP',
    country: 'Russia',
    countryCode: 'RU',
    latitude: 55.7558,
    longitude: 37.6173,
    blocked: true,
  },
  {
    id: '2',
    timestamp: new Date(Date.now() - 1000 * 60 * 10),
    severity: 2,
    category: 'Port Scanning',
    signature: 'ET SCAN Potential SSH Scan',
    srcIp: '103.248.70.123',
    srcPort: 45678,
    destIp: '192.168.1.100',
    destPort: 22,
    protocol: 'TCP',
    country: 'China',
    countryCode: 'CN',
    latitude: 39.9042,
    longitude: 116.4074,
    blocked: true,
  },
  {
    id: '3',
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    severity: 2,
    category: 'Brute Force',
    signature: 'ET POLICY Multiple Failed SSH Logins',
    srcIp: '45.142.212.61',
    srcPort: 33456,
    destIp: '192.168.1.100',
    destPort: 22,
    protocol: 'TCP',
    country: 'Netherlands',
    countryCode: 'NL',
    latitude: 52.3676,
    longitude: 4.9041,
    blocked: true,
  },
  {
    id: '4',
    timestamp: new Date(Date.now() - 1000 * 60 * 20),
    severity: 2,
    category: 'Malware',
    signature: 'ET MALWARE Possible Malicious SSL Cert',
    srcIp: '91.219.237.244',
    srcPort: 443,
    destIp: '192.168.1.100',
    destPort: 443,
    protocol: 'TCP',
    country: 'Ukraine',
    countryCode: 'UA',
    latitude: 50.4501,
    longitude: 30.5234,
    blocked: false,
  },
  {
    id: '5',
    timestamp: new Date(Date.now() - 1000 * 60 * 25),
    severity: 3,
    category: 'Suspicious Activity',
    signature: 'ET INFO Suspicious User-Agent',
    srcIp: '198.50.191.95',
    srcPort: 12345,
    destIp: '192.168.1.100',
    destPort: 80,
    protocol: 'HTTP',
    country: 'United States',
    countryCode: 'US',
    latitude: 37.7749,
    longitude: -122.4194,
    blocked: false,
  },
];

// Mock Rules Data
export const mockRules: Rule[] = [
  {
    id: '1',
    sid: 2100498,
    enabled: true,
    action: 'drop',
    protocol: 'tcp',
    source: 'any',
    destination: '$HOME_NET',
    rule: 'alert tcp any any -> $HOME_NET 22 (msg:"ET SCAN Potential SSH Scan"; flow:to_server; flags:S,12; threshold: type both, track by_src, count 5, seconds 60; reference:url,doc.emergingthreats.net/2001219; classtype:attempted-recon; sid:2001219; rev:20;)',
    description: 'Detects potential SSH scanning activity',
    category: 'Port Scanning',
  },
  {
    id: '2',
    sid: 2100499,
    enabled: true,
    action: 'drop',
    protocol: 'tcp',
    source: 'any',
    destination: '$HOME_NET',
    rule: 'alert tcp any any -> $HOME_NET 22 (msg:"ET POLICY Multiple Failed SSH Logins"; flow:to_server,established; content:"Failed password"; nocase; threshold: type threshold, track by_src, count 5, seconds 60; classtype:attempted-admin; sid:2210020; rev:3;)',
    description: 'Detects multiple failed SSH login attempts',
    category: 'Brute Force',
  },
  {
    id: '3',
    sid: 2100500,
    enabled: true,
    action: 'alert',
    protocol: 'udp',
    source: 'any',
    destination: '$HOME_NET',
    rule: 'alert udp any any -> $HOME_NET 123 (msg:"ET DOS Possible NTP DDoS Inbound Frequent Un-Authed MON_LIST Requests"; content:"|00 00 00 00|"; depth:4; byte_test:1,&,128,0; byte_test:1,&,64,0; byte_test:1,&,4,0; byte_test:1,&,2,0; byte_test:1,&,1,0; threshold: type both, track by_dst, count 3, seconds 3; reference:url,isc.sans.edu/diary/NTP+reflection+attacks/17300; classtype:attempted-dos; sid:2017919; rev:4;)',
    description: 'Detects potential NTP DDoS attack',
    category: 'DDoS Attack',
  },
  {
    id: '4',
    sid: 2100501,
    enabled: false,
    action: 'alert',
    protocol: 'tcp',
    source: 'any',
    destination: '$HOME_NET',
    rule: 'alert tcp any any -> $HOME_NET 80 (msg:"ET MALWARE Possible Malicious SSL Cert"; flow:to_server,established; content:"|16 03|"; depth:2; content:"|01|"; distance:3; within:1; content:"|03|"; distance:1; within:1; classtype:trojan-activity; sid:2023883; rev:2;)',
    description: 'Detects suspicious SSL certificates',
    category: 'Malware',
  },
  {
    id: '5',
    sid: 2100502,
    enabled: true,
    action: 'alert',
    protocol: 'http',
    source: 'any',
    destination: '$HOME_NET',
    rule: 'alert http any any -> $HOME_NET any (msg:"ET INFO Suspicious User-Agent"; flow:to_server,established; content:"User-Agent|3a 20|"; http_header; content:"python-requests"; http_header; nocase; classtype:misc-activity; sid:2024897; rev:1;)',
    description: 'Detects suspicious user agents',
    category: 'Suspicious Activity',
  },
];

// Mock Logs Data
export const mockLogs: LogEntry[] = [
  {
    id: '1',
    timestamp: new Date(Date.now() - 1000 * 60 * 2),
    level: 'info',
    message: 'Suricata started successfully',
    source: 'suricata-main',
  },
  {
    id: '2',
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    level: 'info',
    message: 'Rules updated: 25,432 signatures loaded',
    source: 'suricata-rules',
  },
  {
    id: '3',
    timestamp: new Date(Date.now() - 1000 * 60 * 8),
    level: 'warning',
    message: 'High memory usage detected: 85%',
    source: 'system-monitor',
  },
  {
    id: '4',
    timestamp: new Date(Date.now() - 1000 * 60 * 12),
    level: 'error',
    message: 'Failed to parse rule at line 1234: syntax error',
    source: 'suricata-rules',
  },
  {
    id: '5',
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    level: 'info',
    message: 'Interface eth0 monitoring started',
    source: 'suricata-capture',
  },
];

// Mock System Stats
export const mockSystemStats: SystemStats = {
  cpu: 45,
  memory: 68,
  networkIn: 125.5,
  networkOut: 89.3,
  totalAlerts: 1247,
  blockedIPs: 89,
  activeRules: 25432,
  serviceStatus: 'running',
};

// Mock Blocked IPs
export const mockBlockedIPs: BlockedIP[] = [
  {
    id: '1',
    ip: '185.220.101.45',
    country: 'Russia',
    countryCode: 'RU',
    reason: 'DDoS Attack - Multiple NTP requests',
    blockedAt: new Date(Date.now() - 1000 * 60 * 30),
    duration: 'Permanent',
    alertCount: 156,
  },
  {
    id: '2',
    ip: '103.248.70.123',
    country: 'China',
    countryCode: 'CN',
    reason: 'Port Scanning - SSH scan detected',
    blockedAt: new Date(Date.now() - 1000 * 60 * 45),
    duration: '24 hours',
    alertCount: 89,
  },
  {
    id: '3',
    ip: '45.142.212.61',
    country: 'Netherlands',
    countryCode: 'NL',
    reason: 'Brute Force - Multiple failed SSH logins',
    blockedAt: new Date(Date.now() - 1000 * 60 * 60),
    duration: '12 hours',
    alertCount: 234,
  },
];

// Mock Attack Stats
export const mockAttackStats: AttackStats[] = [
  { type: 'DDoS', count: 456, percentage: 36.5 },
  { type: 'Port Scanning', count: 312, percentage: 25.0 },
  { type: 'Brute Force', count: 289, percentage: 23.2 },
  { type: 'Malware', count: 123, percentage: 9.9 },
  { type: 'Other', count: 67, percentage: 5.4 },
];

// Mock Timeline Data
export const mockTimelineData: TimelineData[] = [
  { timestamp: '00:00', ddos: 12, portScan: 8, bruteForce: 15, malware: 3, other: 2 },
  { timestamp: '02:00', ddos: 18, portScan: 12, bruteForce: 10, malware: 5, other: 3 },
  { timestamp: '04:00', ddos: 25, portScan: 15, bruteForce: 18, malware: 7, other: 4 },
  { timestamp: '06:00', ddos: 32, portScan: 22, bruteForce: 25, malware: 9, other: 6 },
  { timestamp: '08:00', ddos: 45, portScan: 28, bruteForce: 32, malware: 12, other: 8 },
  { timestamp: '10:00', ddos: 38, portScan: 25, bruteForce: 28, malware: 10, other: 7 },
  { timestamp: '12:00', ddos: 42, portScan: 30, bruteForce: 35, malware: 14, other: 9 },
  { timestamp: '14:00', ddos: 35, portScan: 20, bruteForce: 22, malware: 8, other: 5 },
  { timestamp: '16:00', ddos: 28, portScan: 18, bruteForce: 20, malware: 6, other: 4 },
  { timestamp: '18:00', ddos: 22, portScan: 15, bruteForce: 16, malware: 5, other: 3 },
  { timestamp: '20:00', ddos: 30, portScan: 20, bruteForce: 24, malware: 8, other: 5 },
  { timestamp: '22:00', ddos: 20, portScan: 12, bruteForce: 14, malware: 4, other: 2 },
];